config/routes.rb
Apollo::Application.routes.draw do

  devise_for :users
  resources :users, only: [:index]

  resources :products, only: [:index, :edit, :create, :update, :destroy]

  resources :projects, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
    resources :items, only: [:edit, :create, :update, :destroy]
    resources :tasks, only: [:edit, :create, :update, :destroy] do
      patch :toggle_starred, on: :member
      patch :toggle_completed, on: :member
    end
    resources :comments, only: [:create, :destroy]
  end

  resources :print_jobs, only: [:index, :create, :edit, :update, :destroy]

  root to: "projects#index"

  get "calendar", to: "pages#calendar"
  get "changelog", to: "pages#changelog"

end

app/models/print_job.rb
class PrintJob < ActiveRecord::Base
  belongs_to :project

  def total_rewards
    (total_quote && rewards_percentage) ? total_quote * rewards_percentage * 0.01 : 0
  end

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end

end

app/controllers/print_jobs_controller.rb
class PrintJobsController < ApplicationController
  before_action :authenticate_user!

  def index
    @q = PrintJob.search(params[:q])
    @print_jobs = @q.result(distinct: true)
    respond_to do |format|
      format.html
      format.xls
      format.js
    end
  end

  def create
    @print_job = PrintJob.new(print_job_params)
    @print_job.save
    redirect_to :back
  end 

  def edit
    @print_job = PrintJob.find(params[:id])
    respond_to { |format| format.js }
  end

  def update
    @print_job = PrintJob.find(params[:id])
    @print_job.update(print_job_params)
    redirect_to :back
  end

  def destroy
    @print_job = PrintJob.find(params[:id])
    @print_job.destroy
    redirect_to :back
  end

  private

  def print_job_params
    params.require(:print_job).permit(:project_id, :number, :name, :account, :printer, :quantity, :rate, :total_quote, :rewards_percentage, :total_paid, :date_paid, :note)
  end

end

app/views/print_jobs/_edit.html.haml
.modal.fade{id: "edit-printJob-#{print_job.id}-modal", "aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog.modal-lg
    .modal-content

      = form_for print_job do |f|

        .modal-header
          %button.button.close{"data-dismiss" => "modal", "aria-hidden" => "true"} &times;
          %h4 Edit Print Job

        .modal-body

          .row

            .form-group.col-md-2
              %label Job #:
              = f.text_field :number,
                class: "form-control"

            .form-group.col-md-3
              %label Account:
              = f.select :account,
                ["eClinicalWorks", "healow"],
                {},
                class: "form-control"

            .form-group.col-md-5
              %label Job Name:
              = f.text_field :name,
                class: "form-control"

            .form-group.col-md-2
              %label Printer:
              = f.select :printer,
                ["Staples"],
                {},
                class: "form-control"

          .row

            .form-group.col-md-12
              %label Project:
              = f.select :project_id,
                Project.all.order("name").map { |p| [p.name, p.id] },
                { include_blank: true },
                class: "form-control"

          .row

            .form-group.col-md-2
              %label Qty:
              = f.number_field :quantity,
                class: "form-control",
                value: 1,
                min: 1

            .form-group.col-md-2
              %label Rate:
              .input-group
                .input-group-addon $
                = f.number_field :rate,
                  class: "form-control",
                  step: 0.01

          .row

            .form-group.col-md-3
              %label Total Quote:
              .input-group
                .input-group-addon $
                = f.number_field :total_quote,
                  class: "form-control",
                  step: 0.01

            .form-group.col-md-3
              %label Total Paid:
              .input-group
                .input-group-addon $
                = f.number_field :total_paid,
                  class: "form-control",
                  step: 0.01

            .form-group.col-md-2
              %label Rewards %:
              .input-group
                = f.number_field :rewards_percentage,
                  class: "form-control",
                  value: 5
                .input-group-addon %

            .form-group.col-md-3
              %label Date Paid:
              = f.date_field :date_paid,
                class: "form-control"

          .row

            .form-group.col-md-12
              %label Notes:
              = f.text_area :note,
                class: "form-control"

        .modal-footer
          = f.submit "Save Print Job", class: "btn btn-success btn-sm"

app/views/print_jobs/_new.html.haml
#new-printJob-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog.modal-lg
    .modal-content

      - @print_job = PrintJob.new
      = form_for @print_job do |f|

        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} ×
          %h4 New Print Job

        .modal-body

          .row

            .form-group.col-md-2
              %label Job #:
              = f.text_field :number,
                class: "form-control"

            .form-group.col-md-3
              %label Account:
              = f.select :account,
                ["eClinicalWorks", "healow"],
                {},
                class: "form-control"

            .form-group.col-md-5
              %label Job Name:
              = f.text_field :name,
                class: "form-control"

            .form-group.col-md-2
              %label Printer:
              = f.select :printer,
                ["Staples"],
                {},
                class: "form-control"

          .row

            .form-group.col-md-12
              %label Project:
              = f.select :project_id,
                Project.all.order("name").map { |p| [p.name, p.id] },
                { include_blank: true },
                class: "form-control"

          .row

            .form-group.col-md-2
              %label Qty:
              = f.number_field :quantity,
                class: "form-control",
                value: 1,
                min: 1

            .form-group.col-md-2
              %label Rate:
              .input-group
                .input-group-addon $
                = f.number_field :rate,
                  class: "form-control",
                  step: 0.01

          .row

            .form-group.col-md-3
              %label Total Quote:
              .input-group
                .input-group-addon $
                = f.number_field :total_quote,
                  class: "form-control",
                  step: 0.01

            .form-group.col-md-3
              %label Total Paid:
              .input-group
                .input-group-addon $
                = f.number_field :total_paid,
                  class: "form-control",
                  step: 0.01

            .form-group.col-md-2
              %label Rewards %:
              .input-group
                = f.number_field :rewards_percentage,
                  class: "form-control",
                  value: 5
                .input-group-addon %

            .form-group.col-md-3
              %label Date Paid:
              = f.date_field :date_paid,
                class: "form-control"

          .row

            .form-group.col-md-12
              %label Notes:
              = f.text_area :note,
                class: "form-control"

        .modal-footer
          = f.submit "Create Print Job", class: "btn btn-success btn-sm"

app/views/print_jobs/_print_job.html.haml
%tr
  %td.text-center= print_job.number
  %td
    - if print_job.project_id
      = link_to print_job.name, project_path(print_job.project_id)
    - else
      = print_job.name
  %td= print_job.account
  %td= print_job.printer
  %td.text-center= print_job.quantity
  %td.text-center= number_to_currency(print_job.rate)
  %td.text-center= number_to_currency(print_job.total_quote)
  %td.text-center= "#{print_job.rewards_percentage}%"
  %td.text-center= number_to_currency(print_job.total_rewards)
  %td.text-center= number_to_currency(print_job.total_paid)
  %td.text-center= print_job.date_paid.strftime("%D") if print_job.date_paid
  %td
    = link_to edit_print_job_path(print_job),
      remote: true,
      data: { title: "Edit Print Job", toggle: "tooltip", placement: "bottom" },
      class: "button btn btn-xs btn-warning" do
      %i.fa.fa-pencil

    = link_to print_job,
      method: :delete,
      data: { title: "Delete Print Job", toggle: "tooltip", placement: "bottom", confirm: "Are you sure you want to delete this Print Job?" },
      class: "button btn btn-xs btn-danger" do
      %i.fa.fa-trash

app/views/print_jobs/edit.js.erb
if ($("#edit-printJob-"+<%= @print_job.id %>+"-modal").length == 0) {
  $("body").append("<%= j render "print_jobs/edit", print_job: @print_job %>")
}
$("#edit-printJob-"+<%= @print_job.id %>+"-modal").modal("show")

app/views/print_jobs/index.html.haml
.col-md-12

  .panel.panel-default

    .panel-heading
      %h4
        %i.fa.fa-print
        Print Jobs
        %button.btn.btn-success.btn-sm.btn-margin.pull-right{data: { toggle: "modal", target: "#new-printJob-modal" } }
          %i.fa.fa-plus-circle.btn-margin
          Create a new print job 
        = link_to print_jobs_path(format: "xls"),
          class: "btn btn-primary btn-sm btn-margin pull-right" do
          %i.fa.fa-download.btn-margin
          Download as XLS

    .panel-body
      = search_form_for @q, remote: true do |f|

        .form-group.col-md-4
          %label Search:
          = f.text_field :number_or_name_cont,
            class: "form-control input-sm",
            onkeyup: "$(this).parents('form').trigger('submit.rails')"

        .form-group.col-md-2
          %label Account:
          = f.select :account_cont,
            options_for_select([["eClinicalWorks", "eClinicalWorks"],["healow", "healow"]], params[:account]),
            {include_blank: "All Accounts"},
            class: "form-control input-sm",
            onchange: "$(this).parents('form').trigger('submit.rails');"

        .form-group.col-md-2
          %label From:
          = f.date_field :date_paid_gteq,
            class: "form-control input-sm",
            onchange: "$(this).parents('form').trigger('submit.rails');"

        .form-group.col-md-2
          %label To:
          = f.date_field :date_paid_lteq,
            class: "form-control input-sm",
            onchange: "$(this).parents('form').trigger('submit.rails');"

        %br
        %br

      %table.table.table-hover.table-responsive
        %thead
          %tr
            %th.text-center= sort_link(@q, :number, "#")
            %th= sort_link(@q, :name, "Name")
            %th= sort_link(@q, :account, "Account")
            %th= sort_link(@q, :printer, "Printer")
            %th.text-center= sort_link(@q, :quantity, "Qty")
            %th.text-center= sort_link(@q, :rate, "Rate")
            %th.text-center= sort_link(@q, :total_quote, "Total Quote")
            %th.text-center= sort_link(@q, :rewards_percentage, "Rewards %")
            %th.text-center= sort_link(@q, :total_rewards, "Total Rewards")
            %th.text-center= sort_link(@q, :total_paid, "Total Paid")
            %th.text-center= sort_link(@q, :date_paid, "Date Paid")
            %th Actions
        %tbody= render @print_jobs

= render "new"

app/views/print_jobs/index.js.erb
$("tbody").html("<%= j render @print_jobs %>") 

app/views/print_jobs/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">

  <Worksheet ss:Name="eCW Print Jobs">
    <Table>

      <Row>
        <Cell><Data ss:Type="String">#</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Account</Data></Cell>
        <Cell><Data ss:Type="String">Printer</Data></Cell>
        <Cell><Data ss:Type="String">Qty</Data></Cell>
        <Cell><Data ss:Type="String">Rate</Data></Cell>
        <Cell><Data ss:Type="String">Total Quote</Data></Cell>
        <Cell><Data ss:Type="String">Rewards</Data></Cell>
        <Cell><Data ss:Type="String">Total Rewards</Data></Cell>
        <Cell><Data ss:Type="String">Total Paid</Data></Cell>
        <Cell><Data ss:Type="String">Date Paid</Data></Cell>
      </Row>

      <% @print_jobs.each do |print_job| %>
        <Row>
          <Cell><Data ss:Type="String"><%= print_job.number %></Data></Cell>
          <Cell><Data ss:Type="String"><%= print_job.name %></Data></Cell>
          <Cell><Data ss:Type="String"><%= print_job.account %></Data></Cell>
          <Cell><Data ss:Type="String"><%= print_job.printer %></Data></Cell>
          <Cell><Data ss:Type="Number"><%= print_job.quantity %></Data></Cell>
          <Cell><Data ss:Type="Number"><%= print_job.rate %></Data></Cell>
          <Cell><Data ss:Type="Number"><%= print_job.total_quote %></Data></Cell>
          <Cell><Data ss:Type="Number"><%= print_job.rewards_percentage %></Data></Cell>
          <Cell><Data ss:Type="Number"><%= print_job.total_rewards %></Data></Cell>
          <Cell><Data ss:Type="Number"><%= print_job.total_paid %></Data></Cell>
          <Cell><Data ss:Type="String"><%= print_job.date_paid %></Data></Cell>
        </Row>
      <% end %>

    </Table>
  </Worksheet>
</Workbook>