config/routes.rb
Apollo::Application.routes.draw do

  devise_for :users
  resources :users, only: [:index]

  resources :products, only: [:index, :edit, :create, :update, :destroy]

  resources :projects, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
    resources :items, only: [:edit, :create, :update, :destroy]
    resources :tasks, only: [:edit, :create, :update, :destroy] do
      patch :toggle_starred, on: :member
      patch :toggle_completed, on: :member
    end
    resources :comments, only: [:create, :destroy]
  end

  resources :print_jobs, only: [:index, :create, :edit, :update, :destroy]

  root to: "projects#index"

  get "calendar", to: "pages#calendar"
  get "changelog", to: "pages#changelog"

end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :project
	delegate :name, to: :project, prefix: true, allow_nil: true

	belongs_to :user
	delegate :name, to: :user, prefix: true

	belongs_to :item
	delegate :name, to: :item, prefix: true, allow_nil: true

	has_many :notes, as: :noteable

	default_scope { includes(:project, :user, :notes) }
	scope :completed, -> { where(completed: true) }
	scope :incomplete, -> { where(completed: false) }

	validates :name, presence: true

	date_time_attribute :due_date, time_zone: "Eastern Time (US & Canada)"

  def item_tasks
    if item then item.tasks else project.tasks.general end
  end

	def self.general
    where(:item_id => nil)
  end

  def late?
    due_date && due_date < DateTime.now
  end

  def self.sort_by_priority_and_due_date
    where(starred: true).sort_by_due_date +
    where(starred: false).sort_by_due_date
  end

  def self.sort_by_due_date
    where.not(due_date: nil).order("due_date, name") +
    where(due_date: nil).order("created_at, name")
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def edit
    @task = Task.find(params[:id])
    respond_to { |format| format.js }
  end

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.create(task_params)
    @task.update(created_by: current_user.id)
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Task was successfully created.' }
      format.js
    end
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    respond_to do |format|
      format.html { redirect_to @task.project, notice: 'Task was successfully updated.' }
      format.js
    end
  end

  def toggle_starred
    @task = Task.find(params[:id])
    @task.update(starred: @task.starred.!)
    respond_to { |format| format.js }
  end

  def toggle_completed
    @task = Task.find(params[:id])
    @task.update(completed: @task.completed.!)
    @task.update(completed_at: DateTime.now, starred: false) if @task.completed
    respond_to { |format| format.js }
  end
  

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    respond_to do |format|
      format.html { redirect_to @task.project }
      format.js
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :due_date, :due_date_date, :due_date_time, :completed, :project_id, :user_id, :item_id, :starred, :completed_at, :created_by)
  end

  def param_updated?(param_name) task_params[param_name].present? end

end

app/views/tasks/_edit.html.haml
.modal.fade{id: "edit-task-#{task.id}-modal", "aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content

      = form_for [task.project, task] do |f|

        .modal-header
          %button.button.close{"data-dismiss" => "modal", "aria-hidden" => "true"} &times;
          %h4 Edit Task 

        .modal-body

          .row

            .form-group.col-md-12
              %label Task: 
              = f.text_field :name,
                class: "form-control",
                required: true

          .row

            .form-group.col-md-6
              %label Created At:
              %p= print_date(task.created_at, "xl")

            .form-group.col-md-6
              %label Due Date:
              = f.datetime_local_field :due_date,
                class: "form-control"

          .row

            .form-group.col-md-6
              %label Project:
              %p= link_to "[#{task.project.product_name}] #{task.project_name}", task.project

            .form-group.col-md-6
              %label Item
              = f.collection_select :item_id,
                task.project.items.uniq, :id, :name,
                { required: true, include_blank: "General" },
                { class: "form-control input-sm" }

          .row

            .form-group.col-md-6
              %label Assigned:
              = f.collection_select :user_id,
                task.project.users.uniq, :id, :name,
                { required: true },
                { class: "form-control input-sm" }

            .form-group.col-md-3
              %label Starred?
              %p= f.check_box :starred

            .form-group.col-md-3
              %label Status:
              %p= task.completed ? "Completed" : "Incomplete"

        .modal-footer
          = f.submit "Save Project", class: "btn btn-sm btn-success"

app/views/tasks/_new.html.haml
%center

  - @project ||= item.project

  = form_for [@project, @project.tasks.new], html: { class: "form-inline add-task" }, remote: true do |f|

    .form-group
      %i.fa.fa-level-up.fa-rotate-90
      .add-task-title
        Add Task

      = f.hidden_field :item_id, value: item ? item.id : nil

      = f.text_field :name,
        placeholder: "Task Name",
        required: true,
        class: "form-control input-sm add-task-name"

      = f.collection_select :user_id, @project.users.uniq, :id, :name,
        { required: true, selected: current_user.id },
        { class: "form-control input-sm add-task-user" }

      = link_to "javascript:;",
        data: { toggle: "tooltip", placement: "bottom", title: "Add Due Date" },
        onclick: "$(this).hide(); $(this).siblings().show(); $(this).siblings('#addTask-timefield').hide();",
        class: "btn btn-sm btn-default" do
        %i.fa.fa-calendar

      = f.date_field :due_date_date,
        id: "addTask-datefield",
        class: "form-control input-sm",
        onchange: "$(this).siblings('#addTask-timefield').val('17:00:00.000');"

      = link_to "javascript:;",
        data: { toggle: "tooltip", placement: "bottom", title: "Add Due Time" },
        onclick: "$(this).hide(); $(this).siblings('#addTask-timefield').show();",
        id: "addTask-timeBtn",
        class: "btn btn-sm btn-default" do
        %i.fa.fa-clock-o

      = f.time_field :due_date_time,
        id: "addTask-timefield",
        class: "form-control input-sm"

      = f.submit "Add Task", class: "btn btn-sm btn-default"
                                  
      %button.close.pull-right{data: { target: "#item-#{ item ? item.id : 0 }-addTask", toggle: "collapse" }, type: "button"} &times;

app/views/tasks/_task.html.haml
%li.task{class: "#{'task-late' if task.late? && !task.completed} #{'task-completed' if task.completed}", id: "task-#{task.id}"}

  .task-starred{style: "#{'visibility: hidden;' if task.completed}"}
    = link_to toggle_starred_project_task_path(task.project, task), method: :patch, remote: true do
      %i.fa{class: "#{task.starred ? 'fa-star' : 'fa-star-o'}"}

  = link_to toggle_completed_project_task_path(task.project, task),
    method: :patch,
    remote: true,
    disabled: task.user != current_user,
    class: "task-checkbox" do
    = check_box_tag "completed", 1, task.completed

  .task-name= task.name

  .task-user
    = "(#{task.user_name})" if task.user != current_user

  %ul.tools-dropdown
    %li.dropdown
      %a.dropdown-toggle{href: "#", data: { toggle: "dropdown" } }
        %i.fa.fa-angle-down
      %ul.dropdown-menu
        %li
          = link_to edit_project_task_path(task.project, task), remote: true do
            %i.fa.fa-pencil
        %li
          = link_to [task.project, task], method: :delete, data: { confirm: "Are you sure?" }, remote: true do
            %i.fa.fa-trash-o

  - if task.completed
    .task-date= " Completed #{print_date(task.completed_at, 's')}"
  - elsif task.due_date
    .task-date= " due #{print_date(task.due_date, 's')}"

app/views/tasks/create.js.erb
<% item_id = @task.item_id || 0 %>

$("#item-"+<%= item_id %>+"-tasks").html("<%= j render "items/tasks", { tasks: @task.item_tasks, item_id: item_id } %>");
$("#item-"+<%= item_id %>+"-addTask").find("form").trigger("reset");
$("#item-"+<%= item_id %>+"-addTask").find(".add-task-name").focus();

$("#task-"+<%= @task.id %>).addClass("animated fadeIn");

app/views/tasks/destroy.js.erb
$("#task-"+<%= @task.id %>).addClass("animated fadeOut").delay(200).slideUp();

setTimeout(function(){
  <% item_id = @task.item_id || 0 %>
  $("#item-"+<%= item_id %>+"-tasks").html("<%= j render "items/tasks", { tasks: @task.item_tasks, item_id: item_id } %>");
},750);

app/views/tasks/edit.js.erb
if ($("#edit-task-"+<%= @task.id %>+"-modal").length == 0) {
	$("body").append("<%= j render "tasks/edit", task: @task %>")
}
$("#edit-task-"+<%= @task.id %>+"-modal").modal("show")

app/views/tasks/toggle_completed.js.erb
<% item_id = @task.item_id || 0 %>

<% if @task.completed %>
	$("#task-"+<%= @task.id %>).addClass("task-completed");
<% else %>
  $("#task-"+<%= @task.id %>).removeClass("task-completed");
<% end %>

$("#task-"+<%= @task.id %>).addClass("animated fadeOut").slideUp();

setTimeout(function(){
	$("#item-"+<%= item_id %>+"-tasks").html("<%= j render "items/tasks", { tasks: @task.item_tasks, item_id: item_id } %>");
},500);

app/views/tasks/toggle_starred.js.erb
<% if @task.item_id? %>
	$("#task-"+<%= @task.id %>).parents(".tasks-list").html("<%= j render @task.item.tasks.incomplete.sort_by_priority_and_due_date %>");
<% else %>
	$("#task-"+<%= @task.id %>).parents(".tasks-list").html("<%= j render @task.project.tasks.general.incomplete.sort_by_priority_and_due_date %>");
<% end %>

$("#task-"+<%= @task.id %>).addClass("animated fadeIn");

app/views/tasks/update.js.erb
$("#task-"+<%= @task.id %>).replaceWith("<%= j render "task", task: @task %>")