config/routes.rb
Apollo::Application.routes.draw do

  devise_for :users
  resources :users, only: [:index]

  resources :products, only: [:index, :edit, :create, :update, :destroy]

  resources :projects, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
    resources :items, only: [:edit, :create, :update, :destroy]
    resources :tasks, only: [:edit, :create, :update, :destroy] do
      patch :toggle_starred, on: :member
      patch :toggle_completed, on: :member
    end
    resources :comments, only: [:create, :destroy]
  end

  resources :print_jobs, only: [:index, :create, :edit, :update, :destroy]

  root to: "projects#index"

  get "calendar", to: "pages#calendar"
  get "changelog", to: "pages#changelog"

end

app/models/project.rb
class Project < ActiveRecord::Base
	include DateTimeAttribute
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller.current_user }

	belongs_to :product
  delegate :name, to: :product, prefix: true

	has_many :tasks, dependent: :destroy
	has_many :items, dependent: :destroy
	has_many :comments, dependent: :destroy

  has_many :assignments, dependent: :destroy
	has_many :users, through: :assignments
	accepts_nested_attributes_for :assignments, :reject_if => lambda { |a| a[:user_id].blank? }, allow_destroy: true

	validates :name, presence: true
	validates :product_id, presence: true

	default_scope { includes(:users, :product) }
	scope :active, -> { where(status: ["In Progress", "Waiting", "On Hold", "In Queue"]) }
	scope :completed, -> { where(status: ["Completed", "Cancelled"]) }
	scope :unassigned, -> { includes(:assignments).where(assignments: { user_id: nil }) }

	date_time_attribute :due_date, time_zone: "Eastern Time (US & Canada)"

  before_save :set_end_date, if: :status_changed?

  def set_end_date
    self.end_date = active? ? nil : DateTime.now
  end

	def creator
    User.find(self.created_by)
  end

	def self.sort_by_priority_and_status
    where(starred: true).sort_by_status +
    where(starred: false).sort_by_status
	end

  def self.sort_by_status
    where(status: "In Progress").order("due_date, name") +
    where(status: "Waiting").order("due_date, name") +
    where(status: "On Hold").order("due_date, name") +
    where(status: "In Queue").order("due_date, name") +
    where(status: "Completed").order("end_date, name") +
    where(status: "Cancelled").order("end_date, name")
  end

  def active?
    ["In Progress", "Waiting", "On Hold", "In Queue"].include? status
  end

	def late?
    active? && due_date && due_date < DateTime.now
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!
	before_action :set_project, only: [:show, :edit, :update, :destroy, :update_status_of]

	def index
    @q = Project.all.search(params[:q])
    @q.users_name_eq = current_user.name unless params[:q] && params[:q][:users_name_eq]
    @projects = @q.result(distinct: true)

    @projects = @projects.active unless params[:q] && params[:q][:status_eq]

    @projects = @projects.sort_by_priority_and_status unless params[:q] && params[:q][:s]

    respond_to do |format|
      format.html
      format.js
    end

	end

	def show
	end

	def new
		@project = Project.new
		@assignment = @project.assignments.build
	end

	def edit
    respond_to { |format| format.js }
	end

	def create
		@project = Project.new(project_params)

		if @project.save
			redirect_to project_path(@project)
		else
      redirect_to :back
		end
	end

	def update
		@project.update(project_params)
    respond_to do |format|
      format.html { redirect_to :back, notice: "Project was successfully updated." }
      format.js
    end
	end

	def destroy
		@project.destroy
		redirect_to projects_url
	end

	private

	def set_project
		@project = Project.find(params[:id])
	end

	def project_params
		params.require(:project).permit(:name, :due_date, :due_date_date, :due_date_time, :end_date, :starred, :assigned_by, :description, :product_id, :status, :created_by, user_ids: [])
	end

end

app/views/projects/_edit.html.haml
.modal.fade{id: "edit-project-#{project.id}-modal", "aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog.modal-lg
    .modal-content

      = form_for project do |f|

        .modal-header
          %button.button.close{"data-dismiss" => "modal", "aria-hidden" => "true"} &times;
          %h4 Edit Project

        .modal-body

          .row

            .form-group.col-md-4
              %label Product:
              = f.collection_select :product_id,
                Product.all.sort_by {|p| p.name.downcase }, :id , :name,
                { include_blank: "Select Product", required: true },
                { class: "form-control" }

            .form-group.col-md-8
              %label Project Name:
              = f.text_field :name,
                class: "form-control",
                required: true

          .row

            .form-group.col-md-12
              %label Description:
              = f.text_area :description,
                class: "form-control",
                rows: "7"

          .row

            .form-group.col-md-3
              %label Due Date:
              = f.date_field :due_date_date, class: "form-control"

            .form-group.col-md-3
              %label Due Time:
              = f.time_field :due_date_time, class: "form-control"

            .form-group.col-md-3
              %label Assigned By:
              = f.text_field :assigned_by, class: "form-control"

            .form-group.col-md-3
              %label Status:
              = f.select :status,
                [["In Queue"], ["In Progress"], ["Waiting"], ["On Hold"], ["Cancelled"], ["Completed"]],
                {},
                { class: "form-control" }

          .row

            .form-group.col-md-12
              %label Users Assigned:
              = hidden_field_tag "project[user_ids][]", nil
              - User.all.order("name").each do |user|
                %br
                = check_box_tag "project[user_ids][]", user.id, @project.user_ids.include?(user.id)
                = user.name

        .modal-footer
          = link_to "Delete this Project", project, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-danger"
          = f.submit "Save Project", class: "btn btn-sm btn-success"

app/views/projects/_general_tasks.html.haml
%li#item-general.item
  %h4.item-main
    %i.fa.fa-folder-o.fa-fw.item-type-icon
    .item-name Project Tasks
    = link_to "javascript:;",
      data: { toggle: "collapse", target: "#item-0-addTask" },
      class: "btn btn-default btn-xs add-task-btn pull-right",
      style: "margin-right: 28px;" do
      %i.fa.fa-plus

  #item-0-addTask.collapse= render "tasks/new", item: nil

  - if @project.tasks.general.any?
    #item-0-tasks.tasks-list-box{style: "margin-bottom: 15px;"}
      = render "items/tasks", tasks: project.tasks.general, item_id: 0

app/views/projects/_index.html.haml
= search_form_for q, remote: true do |f|

  .form-group.col-md-4
    %label Search:
    = f.text_field :name_or_product_name_cont,
      class: "form-control input-sm"

  .form-group.col-md-2
    %label Product:
    = f.select :product_name_eq,
      options_for_select(Product.all.map{ |p| [p.name, p.name] }, q.product_name_eq),
      { include_blank: "All Products" },
      class: "form-control input-sm",
      onchange: "$(this).parents('form').trigger('submit.rails');"

  .form-group.col-md-2
    %label Assigned:
    = f.select :users_name_eq,
      options_for_select(User.all.map{ |u| [u.name, u.name] }, q.users_name_eq),
      { include_blank: "All Users" },
      class: "form-control input-sm",
      onchange: "$(this).parents('form').trigger('submit.rails');"

  .form-group.col-md-2
    %label Status:
    = f.select :status_eq,
      options_for_select(statuses.map{ |s| [s, s] }, q.status_eq),
      { include_blank: "All Statuses" },
      class: "form-control input-sm",
      onchange: "$(this).parents('form').trigger('submit.rails');"

  .form-group.col-md-2
    %p.pull-right{style: "margin-top: 29px"}= "#{@projects.count} Projects Found"

%br

%table.table.table-hover.table-responsive
  %thead
    %tr
      %th
        %i.fa.fa-star{style: "color: #666"}
      %th= sort_link(q, :product_name, "Product")
      %th= sort_link(q, :name, "Project")
      %th= sort_link(q, :assigned_by, "Assigned By")
      %th Assigned
      %th.text-center= sort_link(q, :created_at, "Start Date")
      %th.text-center End Date
      %th.text-center= sort_link(q, :status, "Status")
      %th.text-center Actions

  %tbody= render projects

:javascript
  $("#q_name_or_product_name_cont").keyup(function() {
    delay(function(){
      $("#q_name_or_product_name_cont").parents("form").trigger("submit.rails"); 
    }, 500);
  });

  var delay = (function(){
    var timer = 0;
    return function(callback, ms){
      clearTimeout (timer);
      timer = setTimeout(callback, ms);
    };
  })();

app/views/projects/_new.html.haml
#new-project-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog.modal-lg
    .modal-content

      - @project = Project.new

      = form_for @project do |f|

        .modal-header
          %button.button.close{"data-dismiss" => "modal", "aria-hidden" => "true"}
            &times;
          %h4.modal-title#myModalLabel New Project


        .modal-body

          .row
            = f.hidden_field :created_by, value: current_user.id

            .form-group.col-md-4
              %label Product
              = f.collection_select :product_id,
                Product.all.sort_by {|p| p.name.downcase }, :id, :name,
                { include_blank: "Select Product", required: true },
                { class: "form-control" }

            .form-group.col-md-8
              %label Project Name:
              = f.text_field :name,
                placeholder: "Project Name",
                class: "form-control",
                autofocus: true,
                required: true

          .row
            .form-group.col-md-12
              %label Description:
              = f.text_area :description,
                placeholder: "Description",
                class: "form-control",
                rows: "7"

          .row
            .form-group.col-md-3
              %label Due Date:
              = f.date_field :due_date_date,
                class: "form-control",
                onchange: "$('#due-date-time-field').val('17:00:00.000');"

            .form-group.col-md-3
              %label Due Time:
              = f.time_field :due_date_time,
                id: "due-date-time-field",
                class: "form-control"


            .form-group.col-md-4
              %label Assigned By:
              = f.text_field :assigned_by,
                placeholder: "Name",
                class: "form-control"

          .row
            .form-group.col-md-12
              %label Users Assigned:
              = hidden_field_tag "project[user_ids][]", nil
              - User.all.order("name").each do |user|
                %br
                = check_box_tag "project[user_ids][]", user.id, @project.user_ids.include?(user.id)
                = user.name

        .modal-footer
          = f.submit "Add Project", class: "btn btn-sm btn-success"

app/views/projects/_project.html.haml
%tr{id: "project_#{project.id}"}

  %td
    .project-starred
      =link_to project_path(project, project: { starred: project.starred.! }), method: :patch do
        %i.fa{class: "#{project.starred ? 'fa-star' : 'fa-star-o'}"} 

  %td= project.product_name

  %td= link_to project.name, project

  %td= project.assigned_by

  %td= render project.users.uniq

  %td.text-center= project.created_at.strftime("%D")

  %td.text-center
    - if project.end_date
      = project.end_date.strftime("%D")
    - else
      = project.due_date.strftime("%D") if project.due_date

  %td.text-center
    %span.label{class: "label-#{status_label(project.status)}", style: "padding: 5px 10px;"}
      %i.fa.fa-fw{class: "fa-#{status_icon(project.status)}"}
      = project.status

  %td.text-center
    = link_to edit_project_path(project), class: "button btn btn-xs btn-warning", remote: true do
      %i.fa.fa-pencil

app/views/projects/_status.html.haml
.btn-group.project-status
  %button.btn.btn-xs.btn-title.dropdown-btn{type: "button", class: "btn-#{status_label(project.status)}"}
    %i.fa.fa-fw{class: "fa-#{status_icon(project.status)}"}
    = project.status

  %button.btn.btn-xs.dropdown-toggle.dropdown-btn{type: "button", class: "btn-#{status_label(project.status)}", data: { toggle: "dropdown" }}
    %span.caret
    %span.sr-only Toggle Dropdown

  %ul.dropdown-menu.pull-right{role: "menu"}

    - statuses.each do |status_name|
      = link_to project_path(project, project: { status: status_name }), method: :patch do
        %li.dropdown-menu-item
          %i.fa.fa-caret-right{style: "#{'visibility: hidden' unless project.status == status_name}"}
          = status_name

app/views/projects/_table.html.erb
<table class="table projects-table">

	<thead>
		<tr>
			<th width="2%"><i class="fa fa-star" style="color: #666;" %></i></th>
       	<th width="13%">Product</th>
         <th width="23%">Project</th>
         <th width="12%">Assigned By</th>
         <th width="12%">Assigned</th>
         <th width="8%" class="text-center">Start Date</th>
         <th width="8%" class="text-center">Due Date</th>
         <th width="8%" class="text-center">End Date</th>
         <th width="13%" class="text-center">Status</th>
         <th width="1%"></th>
    	</tr>
	</thead>

	<tbody>
		<% for project in projects %>
			<tr>
				<td><%= render "projects/starred", :project => project %></td>
				<td><%= link_to project.product_name, project.product %></td>
				<td><%= link_to project.name, project %></td>
				<td><%= project.assigned_by %></td>
				<td>
					<% if project.has_users %>
						<% for u in project.users.uniq %>
							<%= render "users/photo", :user => u %>
						<% end %>
					<% else %>
						None
					<% end %>
				</td>
				<td class="text-center"><%= print_date(project.created_at, "s") %></td>
				<td class="text-center <%= 'project-late' if project.late? %>">
					<%= print_date(project.due_date, "s") if project.due_date %>
				</td>
				<td class="text-center"><%= print_date(project.end_date, "s") if project.end_date %></td>
				<td class="text-center"><%= render "projects/status", :project => project %></td>
				<td class="edit-cog"><%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_project_path(project) %></td>
			</tr>
		<% end %>
	</tbody>

</table>

app/views/projects/edit.js.erb
if ($("#edit-project-"+<%= @project.id %>+"-modal").length == 0) {
	$("body").append("<%= j render "projects/edit", :project => @project %>")
}
$("#edit-project-"+<%= @project.id %>+"-modal").modal("show")

app/views/projects/index.html.haml
.col-md-12

  .panel.panel-default

    .panel-heading
      %h4
        %i.fa.fa-folder-o
        Projects
        %button.btn.btn-success.btn-sm.btn-margin.pull-right{data: { toggle: "modal", target: "#new-project-modal" } }
          %i.fa.fa-plus-circle.btn-margin
          Start a new project

      = render "new"

    .panel-body

      #projects-table
        = render "index", q: @q, projects: @projects

app/views/projects/index.js.erb
$("#projects-table").html("<%= j render 'projects/index', q: @q, projects: @projects %>")

app/views/projects/show.html.haml
.col-md-11{style: "position: fixed; z-index: 1000;"}
  .panel.panel-default.panel-page-header
    .panel-heading
      %h4
        .project-starred
          =link_to project_path(@project, project: { starred: @project.starred.! }), method: :patch do
            %i.fa{class: "#{@project.starred ? 'fa-star' : 'fa-star-o'}"} 
        = link_to "[#{@project.product_name}]", products_path 
        = @project.name.truncate(60)

        .header-block
          %button.btn.btn-xs.btn-warning{data: { toggle: "modal", target: "#edit-project-#{@project.id}-modal" }}
            %i.fa.fa-pencil.btn-margin

        .header-block
          = render "projects/status", project: @project

        .header-block
          %b= @project.end_date ? "End Date:" : "Due Date:"
          - if @project.end_date
            = @project.end_date.strftime("%D")
          - else
            = @project.due_date ? @project.due_date.strftime("%D") : "None"

        .header-block
          %b Start Date: 
          = @project.created_at.strftime("%D")

        .header-block
          %b Assigned:
          = render @project.users.uniq

        .header-block
          %b Assigned By:
          = @project.assigned_by.present? ? @project.assigned_by : "No One"

      = render "projects/edit", project: @project

.col-md-7{style: "padding-top: 55px;"}

  .panel.panel-default.project-tasks-panel
    .panel-heading
      .panel-title
        Project Tasks
        %button.btn.btn-sm.btn-success.pull-right{data: { toggle: "collapse", target: "#addItem" }}
          %i.fa.fa-plus-circle.btn-margin
          Create a new item 

    .panel-body
      #addItem.collapse= render partial: "items/new"
      %ul.items-list
        = render "projects/general_tasks", project: @project
        = render @project.items.order("created_at")

.col-md-5{style: "padding-top: 55px;"}

  .panel.panel-default.project-details-panel

    .panel-heading
      .panel-title
        Project Details

    .panel-body

      .row
        .col-md-12.project-description
          - if @project.description.length != 0
            = @project.description.gsub(/\n/, '<br>').html_safe
          - else
            %i No description provided

  = render "comments/project_comments", project: @project

app/views/projects/update.js.erb
$("#project_"+<%= @project.id %>).replaceWith("<%= j render @project %>")