config/routes.rb
Apollo::Application.routes.draw do

  devise_for :users
  resources :users, only: [:index]

  resources :products, only: [:index, :edit, :create, :update, :destroy]

  resources :projects, only: [:index, :show, :new, :edit, :create, :update, :destroy] do
    resources :items, only: [:edit, :create, :update, :destroy]
    resources :tasks, only: [:edit, :create, :update, :destroy] do
      patch :toggle_starred, on: :member
      patch :toggle_completed, on: :member
    end
    resources :comments, only: [:create, :destroy]
  end

  resources :print_jobs, only: [:index, :create, :edit, :update, :destroy]

  root to: "projects#index"

  get "calendar", to: "pages#calendar"
  get "changelog", to: "pages#changelog"

end

app/views/layouts/_flashes.html.haml
- if flash.any?
  - flash.each do |key, value|

    - if value.kind_of?(Array)
      - value.each do |message|
        :javascript
          $.growl("#{message}", { type: "#{key}", allow_dismiss: false, placement: { from: "bottom", align: "right" }, timer: 5000, animate: { enter: "animated bounceIn", exit: "animated fadeOut" } });
    - else
      :javascript
        $.growl("#{value}", { type: "#{key}", allow_dismiss: false, placement: { from: "bottom", align: "right" }, timer: 5000, animate: { enter: "animated bounceIn", exit: "animated fadeOut" } });


- if controller.devise_controller? && resource.errors.any?
  - resource.errors.full_messages.uniq.each do |message|
    :javascript
      $.growl("#{message}", { type: "alert", allow_dismiss: false, placement: { from: "bottom", align: "right" }, timer: 5000, animate: { enter: "animated bounceIn", exit: "animated fadeOut" } });

app/views/layouts/_nav.html.haml
%nav.side-nav.col-md-1

  %center.brand= link_to "apollo", changelog_path

  .user-banner
    = link_to projects_path do
      %center= image_tag current_user.profile_photo.url(:thumb), class: "user-photo profile-photo-large"

  %ul.nav.nav-pills.nav-stacked

    %li.nav-item{class: "#{'selected' if params[:controller] == 'projects'}"}
      = link_to projects_path, data: { keybinding: "p" } do
        %center
          %i.fa.fa-fw.fa-folder-o
          .hidden-sm Projects 

    %li.nav-item{class: "#{'selected' if current_page?(print_jobs_path)}"}
      = link_to print_jobs_path do
        %center
          %i.fa.fa-fw.fa-print
          .hidden-sm Print Jobs

    %li.nav-item{class: "#{'selected' if current_page?(products_path)}"}
      = link_to products_path do
        %center
          %i.fa.fa-fw.fa-shopping-cart
          .hidden-sm Products 

    %li.nav-item{class: "#{'selected' if current_page?(users_path)}"}
      = link_to users_path do
        %center
          %i.fa.fa-fw.fa-users
          .hidden-sm Team 

    %li.nav-item{class: "#{'selected' if current_page?(edit_user_registration_path)}"}
      = link_to edit_user_registration_path do
        %center
          %i.fa.fa-fw.fa-cog
          .hidden-sm Settings 

    %li.nav-item
      = link_to destroy_user_session_path,
        method: :delete do
        %center
          %i.fa.fa-fw.fa-sign-out
          .hidden-sm Log Out

app/views/layouts/_side_nav.html.haml
%nav.side-nav.col-md-2

  .brand= link_to "apollo 1.5", changelog_path
  .user-section
    = link_to projects_path do
      = image_tag current_user.profile_photo.url(:small), class: "profile-photo"
    .user-name.hidden-sm= current_user.name
  %ul.nav.nav-pills.nav-stacked

    %hr

    -# %li{class: "#{'selected' if params[:controller] == 'tasks'}"}
    -#   = link_to tasks_path do
    -#     %i.fa.fa-fw.fa-check-circle
    -#     .inline.hidden-sm Tasks
    -#     %span.badge.hidden-sm= current_user.tasks.incomplete.count
    -#
    -# %hr

    %li{class: "#{'selected' if params[:controller] == 'projects'}"}
      = link_to projects_path, data: { keybinding: "p" } do
        %i.fa.fa-fw.fa-folder-o
        .inline.hidden-sm Projects

    %hr

    -# %li{class: "#{'selected' if current_page?(myCalendar_path)}"}
    -#   = link_to myCalendar_path do
    -#     %i.fa.fa-fw.fa-calendar
    -#     .inline.hidden-sm Calendar
    -#   
    -# %hr


    %li{class: "#{'selected' if current_page?(print_jobs_path)}"}
      = link_to print_jobs_path do
        %i.fa.fa-fw.fa-print
        .inline.hidden-sm Print Jobs

    %hr

    %li{class: "#{'selected' if current_page?(products_path)}"}
      = link_to products_path do
        %i.fa.fa-fw.fa-shopping-cart
        .inline.hidden-sm Products

    %hr

    %li{class: "#{'selected' if current_page?(users_path)}"}
      = link_to users_path do
        %i.fa.fa-fw.fa-users
        .inline.hidden-sm Team

    %hr


    %li{class: "#{'selected' if current_page?(edit_user_registration_path)}"}
      = link_to edit_user_registration_path do
        %i.fa.fa-fw.fa-cog
        .inline.hidden-sm Settings

    %hr

    %li
      = link_to destroy_user_session_path, method: :delete do
        %i.fa.fa-fw.fa-sign-out
        .inline.hidden-sm Log Out

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title eCW apollo
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    
    %link{href: "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css", rel: "stylesheet"}
    %link{href: "http://fonts.googleapis.com/css?family=Orbitron:400,700", rel: "stylesheet"}
    %link{href: "http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,400,300,600,700", rel: "stylesheet"}
    %link{href: "http://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700", rel: "stylesheet"}

  %body{class: "#{user_signed_in? ? 'inside-page' : 'front-page'}", style: "#{' padding-top: 50px;' unless user_signed_in?} "}

    = render "layouts/flashes"

    - if user_signed_in?

      .container-fluid
        .row{style: "margin-top: 0px;"}
          .col-md-1.col-sm-2.hidden-xs
            = render "layouts/nav"

          .col-md-11.col-sm-10{style: "padding-top: 20px;"}
            = yield

    - else
      .container
        = yield